# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

COPY package.json bun.lockb ./
RUN bun install

COPY . .

USER bun
EXPOSE 5173
CMD ["bun", "run", "dev", "--", "--host"]